### ISSUE TITLE
Emptying Mipmaps after LOD update

### ISSUE THREAD

**Issue by Vand3rz** [MassEffectModder/MassEffectModder#12]
In the tutorial updating LOD is the last thing that needs doing after installing textures, but after clicking the button to do so a dialogue box pops up that says you will have to empty mipmaps after updating the LOD. 

Can you please confirm which is to be done last.

**Comment by aquadran** [comment]
I'll re-phrase in the tool to be more clear. You need do this together, order doesn't matter. Once you update LOD settings you need remove empty mipmaps. And you can remove empty mipmaps without updating LODs settings, but in this case you will not get some 4K textures used at high resolution, but in 2k instead for example.
This step you can also do it at begining. Backup game files for next time you modding a game to not repeat this step again.
I put this as last step in tutorial because partial removal of mipmaps is done while replacing textures. So in theory this step should be a bit faster when is executed as last.

**Comment by Vand3rz** [comment]
Ok thanks for the clarification. 

On another note, if I were to install ALOT for example and then download a new update on top would I need to empty mipmaps again?

**Comment by aquadran** [comment]
no needed

**Comment by aquadran** [comment]
fixed, will be included at next release
