### ISSUE TITLE
Not an issue, but something I would like to ask you about.

### ISSUE THREAD

**Issue by cristi1990an** [MassEffectModder/MassEffectModder#30]
So first of all, don't get this wrong, this is not a request or demand or anything, it's just a thing I tried to do and wanted to know if it will be possible in the future. So here it is. I'm the guy from the ME1 MEUTIM thread that was having trouble figuring out why my game kept crashing. It was because the Controller Mod is not compatible with a *manually* installed MEUITM (using MEM, of course). Meaning I also can't install other texture mods other than the .exe version of MEUITM with the Controller Mod. Both authors confirmed it, Dybukk implied there's nothing he can do etc. What I was wondering was if there isn't something you can do (or plan to do) on your side. Mgamerz suggested to build a database on top of a game with the Controller files installed but that's not possible, it always detects them and probably that wouldn't work anyway. Or would it? You would know best.

Again, this is not a request, I just want to know if you plan to do anything about it. If not, that's ok, I can use tpf tools to add other textures and I'll forget about it. But if you plan any fix, I would wait for that. I just wanted to know.

**Comment by aquadran** [comment]
you can not install Controller Mod with MEM. all pcc mods needs to be installed before which MEM detect as not compatible mod. problem with this mods are kind of broken, which prevent texture modding. broken it seems is common for all pcc modded files in all pcc ME1 mods. that means the broken tool is used like me3x. there is a hope for this since engine/game I guess working. so that mean broken part is not affecting as much for game. maybe engine able to fix it. no idea now. I want to look closer on this, so maybe I can do some workaround. but no promosses, at this point I don't know what exactly is wrong.

**Comment by aquadran** [comment]
btw, you can ask me on ALOT discord
